version: '3.8'

services:
  db:
    platform: linux/amd64  
    build:
      context: .
      dockerfile: ./backend/mysql.Dockerfile
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MyThesisD@ta2025
      MYSQL_DATABASE: database
      MYSQL_USER: username
      MYSQL_PASSWORD: myThesisDAT@2025
    networks:
      - login_net
    volumes:
      - db_data2:/var/lib/mysql
    restart: always

  php:
    build:
      context: .
      dockerfile: ./frontend/php.Dockerfile
    ports:
      - "80:80"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: username
      MYSQL_PASSWORD: myThesisDAT@2025
      MYSQL_DATABASE: database
    volumes:
      - ./frontend/default:/etc/php/sites-available/default
      - ./frontend/src:/var/www/html
    depends_on:
      - db
    networks:
      - login_net
    restart: always

  extra-db:
    image: mysql:5.7
    platform: linux/amd64  
    container_name: data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MyThesisd@t@2025
      MYSQL_DATABASE: data
      MYSQL_USER: user
      MYSQL_PASSWORD: MyThesisD@t@2025
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - extra_net

networks:
  login_net:
  extra_net:

volumes:
  db_data2:
  mysql-db: